name: Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: builddep
      run:  apt -qy install debhelper liballegro4-dev
    - name: make
      run: |
        id
        gcc --version
        ld --version
        make
